CREATE TABLE model_work_table (
    bet_id TEXT,
    timestamp TEXT,
    ev_percent REAL,
    event_time TEXT,
    event_teams TEXT,
    sport_league TEXT,
    bet_type TEXT,
    description TEXT,
    first_odds INTEGER,
    final_odds INTEGER,
    line_movement INTEGER,
    sportsbook TEXT,
    bet_size REAL,
    win_probability REAL,
    result TEXT,
    time_to_event REAL,
    market_implied_prob REAL,
    clv_percent REAL,
    bet_time_category TEXT,
    -- Player identification
    player_name TEXT,
    games_played_season INTEGER,
    health_score REAL,
    -- Points stats
    points_last_5_avg REAL,
    points_last_5_std REAL,
    points_last_10_avg REAL,
    points_last_10_std REAL,
    points_last_20_avg REAL,
    points_last_20_std REAL,
    points_season_avg REAL,
    points_trend REAL,
    -- Rebounds stats
    rebounds_last_5_avg REAL,
    rebounds_last_5_std REAL,
    rebounds_last_10_avg REAL,
    rebounds_last_10_std REAL,
    rebounds_last_20_avg REAL,
    rebounds_last_20_std REAL,
    rebounds_season_avg REAL,
    rebounds_trend REAL,
    -- Assists stats
    assists_last_5_avg REAL,
    assists_last_5_std REAL,
    assists_last_10_avg REAL,
    assists_last_10_std REAL,
    assists_last_20_avg REAL,
    assists_last_20_std REAL,
    assists_season_avg REAL,
    assists_trend REAL,
    -- Steals stats
    steals_last_5_avg REAL,
    steals_last_5_std REAL,
    steals_last_10_avg REAL,
    steals_last_10_std REAL,
    steals_last_20_avg REAL,
    steals_last_20_std REAL,
    steals_season_avg REAL,
    steals_trend REAL,
    -- Blocks stats
    blocks_last_5_avg REAL,
    blocks_last_5_std REAL,
    blocks_last_10_avg REAL,
    blocks_last_10_std REAL,
    blocks_last_20_avg REAL,
    blocks_last_20_std REAL,
    blocks_season_avg REAL,
    blocks_trend REAL,
    -- Turnovers stats
    turnovers_last_5_avg REAL,
    turnovers_last_5_std REAL,
    turnovers_last_10_avg REAL,
    turnovers_last_10_std REAL,
    turnovers_last_20_avg REAL,
    turnovers_last_20_std REAL,
    turnovers_season_avg REAL,
    turnovers_trend REAL,
    -- Made threes stats
    made_threes_last_5_avg REAL,
    made_threes_last_5_std REAL,
    made_threes_last_10_avg REAL,
    made_threes_last_10_std REAL,
    made_threes_last_20_avg REAL,
    made_threes_last_20_std REAL,
    made_threes_season_avg REAL,
    made_threes_trend REAL,
    -- Consistency scores
    points_consistency REAL,
    rebounds_consistency REAL,
    assists_consistency REAL,
    steals_consistency REAL,
    blocks_consistency REAL,
    turnovers_consistency REAL,
    made_threes_consistency REAL,
    UNIQUE (bet_id, timestamp) ON CONFLICT REPLACE
) 